### ISSUE TITLE
Extend the committee by 2 more seats

### ISSUE THREAD

**Issue by runcom** [moby/tsc#16]
Hello everyone,

We would like to propose increasing the current seats to 9 to have more companies represented in the TSC. We believe that Red Hat has contributed and benefited from the docker/moby projects and we look forward to continue doing so in the future with projects like moby and we would like to represent our communities on the committee. In light of that I’m proposing to open up two (2) more seats and call for a vote at the time and choosing of the current steering committee members.

What do you think?

@crosbymichael @estesp @thaJeztah

**Comment by estesp** [comment]
First, the entire TSC finds it difficult to receive a request to change the TSC formulation immediately after a vote which closed mere days ago. This comes after nearly two months **[1]** comprised of 1) a feedback period on the initial TSC charter, 2) a sufficiently long and open call for candidates, culminating with 3) a series of project and final votes that only wrapped this past Friday, November 10th. The initial TSC has a bit of work ahead of us to formulate our initial internal organization and any processes we want to set up to handle the work assigned to us in the charter. We would prefer to focus on that initial work rather than re-open the discussion of the initial TSC charter and, specifically, the TSC size at this time.
 
This initial vote has generated representation from six different companies of significantly varied size, with, per the charter, only two seats maximum (one-third of 7) available to a single vendor. While we fully agree that Red Hat has made considerable contributions to Docker and the Moby project over the years and has had continued maintainership in the core project, a request to immediately provide new TSC seats with the stated expectation of providing them for specific company representation seems quite unusual. More specifically, given Red Hat was fully included in the process just completed—in the same way as any other maintainer-represented employer across the Moby projects—it would be expected that you would provide candidate nominations to achieve TSC representation during that publicly announced process. Given we have very broad diversity with six unique employers of the initial TSC representatives, we don’t see a valid argument for immediate expansion of the TSC to satisfy a specific desire for representation outside the process.
 
Finally, given the clear responsibilities of this TSC, quoted directly from our [governance charter](https://github.com/moby/tsc/blob/master/README.md#responsibilities):

 1. *Serve as an escalation point for members of the community to file a dispute or report concerns on technical issues.*
 2. *Ensure that appropriate communication exists between projects.*
 3. *Keep a public record of escalations, actions, and decisions.*

I would hope that representation directly from any one company is not required to make sure that all participants across the Moby umbrella of projects are represented appropriately as to the matters listed above. To be as clear as possible, the TSC’s response to a concern from Red Hat or any other vendor should be as equitable and as capable to represent those issues without direct company representation, and to determine appropriate action in a fair and equitable matter for all parties. If we can’t do that for Red Hat, how can we do that for any representative vendor or participant across the community without direct TSC membership?
 
Of course, we expect and hope that you and many other candidates will be submitted for the next general election cycle and that representation continues to be as diverse as possible. As we gain some experience as a TSC over the next year, we can always reconsider any issues of representation or TSC size as necessary for the future.

This response has unanimous approval from all seven members of the TSC.
_________
**[1]** Rough timeline:
 - **14 Sep** - new governance announced at Moby Summit L.A. and via Twitter, Michael Crosby provided as direct contact for interested parties to give any feedback on TSC document draft
 - **27 Sep** - TSC initial charter and initial vote announced at https://github.com/moby/tsc.
 - **29 Sep** - all maintainers of any Moby umbrella project received an email inviting them to submit candidates for the initial 7 member TSC.
 - Nominations initially were to close on **6 Oct**, but were extended until **13 Oct**.
 - Per-project voting and issues with the CIVS site caused a late start and added extensions to the voting period: from approx. **18 Oct** through **10 Nov**
 - **13 Nov** Final vote results were announced on Monday

**Comment by runcom** [comment]
Thanks for considering this request.
Just to clarify, I wasn't requesting to immediately provide new TSC seats, rather, just to take that into consideration for the next round of votes. Also, I may have expressed myself wrongly, I was not trying to imply that the TSC can't represent the community without every company sitting in the committee. As I've missed the first round of nominations and votes, I'll make sure to comply with the process next time it occurs.
Thanks for the kind explanation about the whole process.

:blush:

**Comment by estesp** [comment]
Thanks @runcom. Look forward to continue working with you into the future. I'm going to close this as I think we're all good here.
